### ISSUE TITLE
Why does pusher-client gem depend upon EventMachine

### ISSUE THREAD

**Issue by njh** [logankoester/pusher-client#3]
Just wondering why the pusher-client gem depends upon EventMachine.

Just had a look through the source code but couldn't see any mention of it.

**Comment by logankoester** [comment]
Good catch! It was probably a dependency at one point when I first started that is not used any more. Will gladly accept a pull request to remove it.

**Comment by njh** [comment]
Merged in 3d38c8bc6d85602f51a148c003eafb0dbdbeae3b
